service: serverlesswp-wordpress-starter

provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    payload: '2.0'

functions:
  requestHandler:
    handler: api/index.handler
    memorySize: 1024
    timeout: 15
    events:
      - httpApi:
          method: any
          path: /{proxy+}
    environment:
      #DATABASE: 'defaultdb'
      #USERNAME: 'oscar'
      #PASSWORD: '-jKjp-3u7NAVMTxud7LzPg'
      #HOST: 'oro-azul-13892.7tt.aws-us-east-1.cockroachlabs.cloud'